# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x14\x65xpense_manager.grpc\"@\n\rStatusRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x02 \x01(\x05\"e\n\x0eStatusResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x61\x63tive_records\x18\x03 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x04 \x01(\x05\"e\n\x0eReserveRequest\x12\x13\n\x0bresource_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x11\n\trequester\x18\x03 \x01(\t\x12\x19\n\x11lamport_timestamp\x18\x04 \x01(\x05\"\x81\x01\n\x0fReserveResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0ereservation_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x19\n\x11reserved_quantity\x18\x04 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x05 \x01(\x05\"}\n\rUpdateRequest\x12\x11\n\trecord_id\x18\x01 \x01(\t\x12\x16\n\x0ereservation_id\x18\x02 \x01(\t\x12\x12\n\nnew_status\x18\x03 \x01(\t\x12\x12\n\nadjustment\x18\x04 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x05 \x01(\x05\"\x7f\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x11updated_record_id\x18\x03 \x01(\t\x12\x15\n\rcurrent_value\x18\x04 \x01(\x05\x12\x19\n\x11lamport_timestamp\x18\x05 \x01(\x05\x32\xa7\x02\n\x12TransactionService\x12V\n\tGetStatus\x12#.expense_manager.grpc.StatusRequest\x1a$.expense_manager.grpc.StatusResponse\x12^\n\x0fReserveResource\x12$.expense_manager.grpc.ReserveRequest\x1a%.expense_manager.grpc.ReserveResponse\x12Y\n\x0cUpdateRecord\x12#.expense_manager.grpc.UpdateRequest\x1a$.expense_manager.grpc.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSREQUEST']._serialized_start=39
  _globals['_STATUSREQUEST']._serialized_end=103
  _globals['_STATUSRESPONSE']._serialized_start=105
  _globals['_STATUSRESPONSE']._serialized_end=206
  _globals['_RESERVEREQUEST']._serialized_start=208
  _globals['_RESERVEREQUEST']._serialized_end=309
  _globals['_RESERVERESPONSE']._serialized_start=312
  _globals['_RESERVERESPONSE']._serialized_end=441
  _globals['_UPDATEREQUEST']._serialized_start=443
  _globals['_UPDATEREQUEST']._serialized_end=568
  _globals['_UPDATERESPONSE']._serialized_start=570
  _globals['_UPDATERESPONSE']._serialized_end=697
  _globals['_TRANSACTIONSERVICE']._serialized_start=700
  _globals['_TRANSACTIONSERVICE']._serialized_end=995
# @@protoc_insertion_point(module_scope)
