# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x07lb_demo\"!\n\x0bWorkRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\"C\n\tWorkReply\x12\x12\n\nrequest_id\x18\x01 \x01(\x05\x12\x12\n\nhandled_by\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2J\n\rWorkerService\x12\x39\n\rHandleRequest\x12\x14.lb_demo.WorkRequest\x1a\x12.lb_demo.WorkReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKREQUEST']._serialized_start=25
  _globals['_WORKREQUEST']._serialized_end=58
  _globals['_WORKREPLY']._serialized_start=60
  _globals['_WORKREPLY']._serialized_end=127
  _globals['_WORKERSERVICE']._serialized_start=129
  _globals['_WORKERSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
